spring:
  data:
    rest:
      base-path: /services
  main:
    banner-mode: on
server:
  port: 8080
stomp:
  destination:
    topic: /topic
    name:
      incomingRequest: /incomingRequest
  endPoint: /streaming